### ISSUE TITLE
Error: Failed to install 'ggcor' from GitHub

### ISSUE THREAD

**Issue by xigrug** [houyunhuang/ggcor#10]
package ‘digest’ successfully unpacked and MD5 sums checked
Error: Failed to install 'ggcor' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘digest’

请问如何解决的？win10系统

**Comment by houyunhuang** [comment]
这个主要是win系统缓存机制导致的，你重启下r，然后安装提示的包。

或者在安装的时候不要更新包。

**Comment by xigrug** [comment]
> 这个主要是win系统缓存机制导致的，你重启下r，然后安装提示的包。
> 
> 或者在安装的时候不要更新包。

可以了，解决了。多谢！
