### ISSUE TITLE
环状热图如何修改字体大小呢？

### ISSUE THREAD

**Issue by jinhao94** [houyunhuang/ggcor#12]
环状热图的功能很强大， 解决了又“瘦”又长热图的问题，厉害了。
请问环状热图如何修改坐标轴字体大小？
如下图
![图片](https://user-images.githubusercontent.com/35567826/80330950-3c299580-8879-11ea-8cc2-16b78ec0a6d4.png)

十分感谢！

**Comment by houyunhuang** [comment]
不清楚你总共有多少个变量，一般直接导出PDF更好一些。
若是真的变量特别多，需要关闭默认标签（`paxis = "none"`），然后调用`set_p_x/yaxis()`函数来自己设置。

```
library(ggcor)
library(ggplot2)
data <- rand_dataset(obs = 150)
gcor_tbl(data, cluster = TRUE) %>% 
  quickcor(circular = TRUE, open = 30, outer = 0.2, paxis = "none") +
  geom_colour(aes(fill = data), colour = NA) +
  anno_tree() +
  set_p_xaxis(size = 2) +
  set_p_yaxis(size = 2) +
  scale_fill_viridis_c()
```

**Comment by jinhao94** [comment]
Got it！！！ 谢谢！
