### ISSUE TITLE
parallel_layout() function is not found

### ISSUE THREAD

**Issue by Byronxy** [houyunhuang/ggcor#15]
Hi,
I recently installed ggcor via ·```devtools::install_github("houyunhuang/ggcor")```, And package version is ‘0.9.7’. I hope to use `parallel_layout()` function while I could not find this in the current version. Could you help me with it? Thanks a lot!

**Comment by houyunhuang** [comment]
This function has been deprecated,  and you can use `anno_link()` instead:

```
library(ggcor)
library(ggplot2)
data(varespec, package = "vegan")
data(varechem, package = "vegan")
m <- mantel_test(varespec, varechem, 
                 spec.select = list(Spec01 = 1:8, 
                                    Spec02 = 9:20, 
                                    Spec03 = 21:44)) %>% 
  mutate(p.value = cut(p.value, breaks = c(-Inf, 0.05, Inf),
                       labels = c("<0.05", ">=0.05"), right = FALSE))
quickcor(varechem, type = "upper", axis.label.drop = FALSE) +
  geom_square() +
  anno_link(aes(colour = p.value, size = r), data = m, curvature = 0.05) +
  scale_size_area(max_size = 2) +
  scale_colour_manual(values = link_colour_pal(2))
```

**Comment by Byronxy** [comment]
Thanks a lot! As I want to use the parallel layout, is there any example about changing the layout by using `anno_link`?

**Comment by houyunhuang** [comment]
@Byronxy 
The `link_tbl ()` function may solve your problem,  and you can see the help documentation for details.
