### ISSUE TITLE
some function couldn't be found?

### ISSUE THREAD

**Issue by Zhenghong-Wang** [houyunhuang/ggcor#18]
even I successfully install the "ggcor",but also error like follow:
"Error in parallel_layout(., cor_tbl = corr2) : 
  could not find function "parallel_layout"

Error in geom_link(aes(colour = pd, size = rd), data = filter(mantel,  : 
  could not find function "geom_link"

Error in geom_links2(aes(colour = pd, size = rd), data = mantel) : 
  could not find function "geom_links2"
"
I think the code totally from the http://houyun.xyz/post/2020/03/19/ggcor/.  would you like to help me adress it ?thank you very much for your contributions for correaltion analysis and visualization.

**Comment by houyunhuang** [comment]
This feature has been integrated into `anno_link()` function, you can find the corresponding examples from https://mp.weixin.qq.com/s/v75PECxj08jaqIASaJNaXg
