### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by ShixiangWang** [houyunhuang/ggcor#5]
你好，

首先谢谢开发了这么好的工具。我准备在包里使用这个包，有一些疑问。

-  我看到很多函数没有文档，能否添加
-  你准备什么时候提交到CRAN
-  今后的开发变化大吗
-  是否可以支持非相关结果（我有一些离散变量需要可视化，结果是差值而不是相关系数)

祝好，
诗翔

**Comment by houyunhuang** [comment]
你好，基于前期收到的一些意见，目前应该处于大修阶段，不过总体上是增强数据处理的灵活性，尽量保持了前后版本的一致性。

1.master分支除非有bug我不打算做大的变化了，现在都在dev1.0.0分支上进行代码重构。

2.提交cran应该等1.0.0重构完测试一轮了再说。

**Comment by ShixiangWang** [comment]
谢谢~
