### ISSUE TITLE
`type=` is not wroking for cor matrix in ggcor()

### ISSUE THREAD

**Issue by bakerwm** [houyunhuang/ggcor#7]
For example: here is the cor matrix,  the `type=` option in `ggcor()` is not working.

```
> library(ggcor)
> ma
       a      b      c
a 1.0000 0.9972 0.9204
b 0.9972 1.0000 0.9366
c 0.9204 0.9366 1.0000

> df  <- as_cor_tbl(ma)
> ggcor(df, type = "lower") #failed 
> ggcor(df, type = "lower") + 
  geom_color(data = get_data(type = "lower"))
> ggcor(mtcars, type = "lower") # success

> packageVersion("ggcor")
[1] ‘0.7.9’
```

**Comment by houyunhuang** [comment]
It looks like the input is of type `cor_tbl` and it comes straight back to `ggcor()`. I will release a new version soon, and I have addressed this issue. You can install the development version.

```
devtools::install_github("houyunhuang/ggcor", "dev1.0.0")
```

**Comment by bakerwm** [comment]
@houyunhuang  yes, `cor_tbl` as input, will skip some options. 
After reading your source code, I can use `type=` option in `df <- as_cor_tbl()` step to generate the **correct** plot (this is not a code fix, but I can get the correct plot now). Thanks.

```
> ggcor(df, type = "lower") #failed 
> df  <- as_cor_tbl(ma, type = "lower") # success
> ggcor(df)
```
